spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=customer_user
spring.datasource.password=customer_pass
server.port=8082
spring.jpa.hibernate.ddl-auto=update