syntax = "proto3";

package billing.v1;

option java_package = "com.billing.grpc";
option java_multiple_files = true;

service BillService {
  rpc CreateBill(CreateBillRequest) returns (CreateBillResponse);
  rpc GetBill(GetBillRequest) returns (GetBillResponse);
  rpc ListBills(ListBillsRequest) returns (ListBillsResponse);
  rpc PayBill(PayBillRequest) returns (PayBillResponse);
}

message CreateBillRequest { int64 customer_id = 1; string amount = 2; }
message CreateBillResponse { Bill bill = 1; }
message GetBillRequest { int64 id = 1; }
message GetBillResponse { Bill bill = 1; }
message ListBillsRequest {}
message ListBillsResponse { repeated Bill bills = 1; }
message PayBillRequest { int64 id = 1; }
message PayBillResponse { Bill bill = 1; }



message Bill {
  int64 id = 1;
  int64 customer_id = 2;
  string amount = 3;
  bool paid = 4;
  string created_at = 5;
}