spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=billing_user
spring.datasource.password=billing_pass

spring.jpa.hibernate.ddl-auto=update
grpc.server.port=9091

customer.service.host=localhost
customer.service.port=9090